src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan(
     *  "today",
     *  message="La date d'arrivée doit faire au moins la date d'aujourd'hui"
     * )
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan(
     *  propertyPath="startDate",
     *  message="La date de départ doit logiquement être supérieur à la date d'arrivée"
     * )
     */
    private $endDate;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * Permet de calculer la durée de la réservation
     *
     * @return integer
     */
    public function getDuration(): int
    {
        if ($this->startDate && $this->endDate) {
            return $this->endDate->diff($this->startDate)->days;
        }
    }

    /**
     * Sert à remplir automatiquement la date de création et le montant
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function setCreatedAtAndAmountValue(): void
    {        
        if (!$this->createdAt) {
            $this->createdAt = new \DateTime();
        }

        if (!$this->amount) {
            $this->amount = $this->getDuration() * $this->ad->getPrice();
        }
    }

    /**
     * Return true when ad is bookable and false when ad is not
     *
     * @return boolean
     */
    public function isBookableAd(): bool
    {
        $selectedDays = $this->getSelectedDays();

        // Les dates qui sont occupées
        $busyDays = $this->ad->getBusyDays();

        // Les dates sélectionées par l'utilisateur

        // Fonction anonyme qui sert à transformer un tableau d'objet DateTime en string
        $datetimeToString = function($dayTime) {
            return $dayTime->format('Y-m-d');
        };
        
        // Transoformation les deux tableaux dateTime sous la forme de string
        $busyDaysToString = array_map($datetimeToString, $busyDays);

        $selectedDaysToString = array_map($datetimeToString, $selectedDays);

        foreach($selectedDaysToString as $day) {
            if (array_search($day, $busyDaysToString) !== false) return false;
        }

        return true;
    }

    /**
     * Permet connaitre les dates sélectionnées par l'utilisateur
     *
     * @return array
     */
    public function getSelectedDays(): array
    {
        $timestampDate = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 3600
        );

        // Tranfrom $timestampDate to datetime object
        $days = array_map(function($dayTimeStamp) {
            return new \DateTime(date('Y-m-d', $dayTimeStamp));
        }, $timestampDate);

        return $days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use App\Entity\Comment;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Cette addrese s'est déjà inscrit par un autre compte, veuillez taper un autre email"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *  min=3,
     *  max=18,
     *  minMessage="Le prénom doit faire au moins {{ limit }} caractères",
     *  maxMessage="Le prénom ne doit pas dépasser {{ limit }} caractères"
     * )
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *  min=3,
     *  max=18,
     *  minMessage="Le nom doit faire au moins {{ limit }} caractères",
     *  maxMessage="Le nom ne doit pas dépasser {{ limit }} caractères"
     * )
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez taper un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *  groups={"account_register"},
     *  min=8,
     *  max=25,
     *  minMessage="Le mot de passe doit faire au moins {{ limit }} caractères",
     *  maxMessage="Le mot de passe ne doit pas dépasser {{ limit }} caractères"
     * )
     */
    private $password;

    /**
     * @Assert\IdenticalTo(
     *  propertyPath="password",
     *  message="Veuillez confirmer correctement le mot de passe"
     * )
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $avatar;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *  min=300,
     *  minMessage="La description doit faire au moins {{ limit }} caractères"
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="owner", orphanRemoval=true)
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker", orphanRemoval=true)
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * Get Average rating
     *
     * @return integer|null
     */
    public function getAvgRating(): ?int
    {
        if (count($this->ads) > 0) {
            foreach ($this->ads as $ad) {
                $sumRating = array_reduce(
                    $ad->getComments()->toArray(),
                    fn($total, Comment $comment) => $total += $comment->getRating()
                );
    
                if (count($ad->getComments()) > 0) {
                    return ceil($sumRating / count($ad->getComments()));
                }
            }
        }

        return null;
    }

    /**
     * Set automaticaly createdAt value
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function setCreatedAtValue(): void 
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new DateTime();
        }
    }

    /**
     * create and set automaticaly slug value
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function setSlugValue(): void
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify
                            ->slugify($this->id . '-' . $this->firstName . '-' . $this->lastName);
        }
    } 

    /**
     * Retrieve the full name
     *
     * @return string
     */
    public function getFullname(): string 
    {   
        if ($this->firstName && $this->lastName) {
            return $this->firstName . ' ' . $this->lastName;
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPasswordConfirm(): ?string
    {
        return $this->passwordConfirm;
    }

    public function setConfirmPassword(string $passwordConfirm): self
    {
        $this->passwordConfirm = $passwordConfirm;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setOwner($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getOwner() === $this) {
                $ad->setOwner(null);
            }
        }

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->userRoles->map(function(Role $role) {
            return $role->getTitle();
        });

        $roles->add('ROLE_USER');

        return $roles->toArray();
    }

    public function getHash(): string
    {
        return $this->password;
    }

    public function getSalt() {}
    
    public function getUsername(): string
    {
        return $this->email;
    }

    public function eraseCredentials() {}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\DataTransformer\FrenchDateToDateTimeTransformer;
use App\Form\FormHelperType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class BookingType extends AbstractType
{
    use FormHelperType;

    private FrenchDateToDateTimeTransformer $transformer;

    public function __construct(FrenchDateToDateTimeTransformer $transformer)
    {
        $this->transformer = $transformer;
    }
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'startDate',
                TextType::class,
                $this->setValuesOfAttributesForm(
                    "Date d'arrivée",
                    "La date d'arrivée",
                )
            )
            ->add(
                'endDate',
                TextType::class,
                $this->setValuesOfAttributesForm(
                    "Date de départ",
                    "La date de départ",
                )
            )
        ;

        $builder
            ->get('startDate')
            ->addModelTransformer($this->transformer);

        $builder
            ->get('endDate')
            ->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}
   Réservation de {{ ad.title }}
{% endblock %}

{% form_theme form _self %}

{% block stylesheets %}
   <link 
      rel="stylesheet" 
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />
{% endblock %}

{% block body %}
<div class="booking-book vh-100"
   style="background: url(/uploads/thumbnails/{{ ad.thumbnail }}); background-size: cover"
>
   <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
         <div class="col-md-8 col-sm-12">
            <div class="booking-book__form">
               {{ form_start(form) }}
                  <div class="row mb-3">
                     {# Date d'arrivée #}
                     <div class="col">
                        <div class="form-outline">
                           {{ form_widget(form.startDate) }}
                           {{ form_label(form.startDate, null, {
                              'label_attr': {
                                 'class': 'form-label'
                              }
                           }) }}
                           <small class="form-help">{{ form_help(form.startDate) }}</small>
                           {% if form_errors(form.startDate) is not empty %}
                              <div class="form-error mt-3">
                                 {{ form_errors(form.startDate) }}
                              </div>
                           {% endif %}
                        </div>
                        <small class="text-muted {% if form_errors(form.startDate) is not empty %}invisible{% endif %}"><strong>Date valide</strong></small>
                     </div>
                     {# Date de départ #}
                     <div class="col">
                        <div class="form-outline">
                           {{ form_widget(form.endDate) }}
                           {{ form_label(form.endDate, null, {
                              'label_attr': {
                                 'class': 'form-label'
                              }
                           }) }}
                           <small class="form-help">{{ form_help(form.endDate) }}</small>
                           {% if form_errors(form.endDate) is not empty %}  
                              <div class="form-error mt-3">
                                 {{ form_errors(form.endDate) }}
                              </div>
                           {% endif %}
                        </div>
                        <small 
                           class="text-muted {% if form_errors(form.endDate) is not empty %}invisible{% endif %}"
                        >
                           <strong>Date valide</strong>
                        </small>
                     </div>
                  </div>

                  {# Amount and days #}
                  <div class="booking-book__amount mb-4 d-none"></div>

                  {# Submit button #}
                  <button class="btn btn-primary">
                     <i class="fas fa-book mr-2"></i>
                     Réserver
                  </button>
               {{ form_end(form) }}
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

{% block javascripts %}
   <script 
      src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js">
   </script>
   <script>
      $(function() {
         
         $('#booking_startDate, #booking_endDate').datepicker({
            format: 'dd/mm/yyyy',
            datesDisabled: [
               {% for day in ad.busyDays %}
                  "{{ day.format('d/m/Y') }}",
               {% endfor %}
            ],
            startDate: new Date()
         });

         $('#booking_startDate, #booking_endDate').on('change', function() {
            let startDate = new Date($('#booking_startDate').val().replace(/(\d{2})\/(\d{2})\/(\d{4})/, '$3-$2-$1'));
            let endDate = new Date($('#booking_endDate').val().replace(/(\d{2})\/(\d{2})\/(\d{4})/, '$3-$2-$1'));

            const HOUR_TO_MS = 24 * 3600 * 1000;

            if (startDate && endDate && endDate > startDate) {
               let days = (endDate - startDate) / HOUR_TO_MS;

               let amount = days * {{ ad.price }};

               if (days === 1) {
                  $('.booking-book__amount')
                  .removeClass('d-none')
                  .text("Vous avez réservé un jour pour " + amount + ' DH')
               } else {
                  $('.booking-book__amount')
                     .removeClass('d-none')
                     .text("Vous avez réservé " + days + " jours pour " + amount + ' DH')
               }

            } else {
               $('.booking-book__amount').addClass('d-none')
            }
         });
      });
   </script>
{% endblock %}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title "Mes réservations" %}

{% block body %}
<div class="container mt-5">
   <div class="booking-all__header text-center mb-5">
      <h1 class="display-6">Vos réservations</h1>
      <p>Vos réservations sont invisibles pour les autres</p>  
   </div>

   {% if bookings %}
   <div class="row">
      {% for booking in bookings %}
      <div class="col-xl-3 col-md-6 col-sm-12 mb-4">
         {% set url = path("booking_show", {"id": booking.id}) %}
         <div class="card hover-shadow">
            <div 
               class="bg-image hover-overlay ripple"
               data-mdb-ripple-color="light"
               >
               <img
                  src="/uploads/thumbnails/{{ booking.ad.thumbnail }}"
                  class="img-fluid"
                  alt="Img fluid"
               />
               <a href="{{ url }}">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
               </a>
            </div>
            <div class="card-body">
               <h5 class="card-title text-truncate" title="{{ booking.ad.title }}">{{ booking.ad.title }}</h5>
               <p class="card-text overflow-hidden" style="max-height: 47px" title="{{ booking.ad.title }}"><small>{{ booking.ad.introduction }}</small></p>
               <div class="card-body__details">
                  <ul class="list-unstyled text-muted">
                     <li>
                        <small>
                           <i class="fas fa-calendar me-2"></i>{{ booking.startDate|date('j F Y') }}
                        </small>
                     </li>
                     <li>
                        <small>
                           <i class="fas fa-calendar me-2"></i>{{ booking.endDate|date('j F Y') }}
                        </small>
                     </li>
                     <li>
                        <small>
                           <i class="fas fa-money-check-alt me-2"></i>{{ booking.amount }} DH
                        </small>
                     </li>
                     <li>
                        <small>
                           <i class="fas fa-calendar-day me-2"></i>{{ booking.duration }} jours
                        </small>
                     </li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
      {% endfor %}
   </div>
   {% endif %}
</div>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
   Réservation n°{{ booking.id }}
{% endblock %}

{% form_theme form _self %}

{% block body %}

{% set user          = app.user %}
{% set isCommented   = booking.ad.isCommented(user) %}
{% set owner         = booking.ad.owner %}
{% set comment       = booking.ad.isCommented(user) %}

{% if comment != false %}
   {% set rating = comment.rating %}
{% endif %}

<div class="container mt-5">

   <div class="row">
      {# Booking infos #}
      <div class="col-md-7 col-sm-12">
         <section class="booking-infos">
            <h3>Plus de détails sur votre réservation</h3>
            <hr class="my-4">
            <div class="booking-infos__details">
               <ul class="list-unstyled">
                  <li class="mb-2">Réservation n°<strong>{{ booking.id }}</strong></li>
                  <li class="mb-2">Le titre de l'annonce : <strong>{{ booking.ad.title }}</strong></li>
                  <li class="mb-2">la date d'arrivée : <strong>{{ booking.startDate|date('D, d M Y') }}</strong></li>
                  <li class="mb-2">La date de départ <strong>{{ booking.endDate|date('D, d M Y') }}</strong></li>
                  <li class="mb-2">Le nombre de jours d'hébergement : <strong>{{ booking.duration }} jours</strong></li>
                  <li>Le montant est : <strong>{{ booking.amount }} DH</strong></li>
               </ul>
            </div>
         </section>
      </div>
      <div class="col-md-1">
         <div class="vertical-separator"></div>
      </div>
      {# Booking owner #}
      <div class="col-md-4 col-sm-12">
         <section class="booking-owner">
            <h3>Infos sur l'hôte</h3>
            <hr class="my-3">
            <div class="row">
               <div class="col-4">
                  <div class="booking-owner__avatar text-center">
                     <small>
                        <strong class="mb-3">{{ owner.fullname }}</strong>
                     </small>
                     <img 
                        src="/uploads/avatars/{{ owner.avatar }}" 
                        alt="Photo de profil de {{ owner.fullname }}" 
                        class="rounded-circle w-100">
                  </div>
               </div>
               <div class="col d-flex align-items-center">
                  <ul class="list-unstyled m-0">
                     <li class="mb-2"><i class="fas fa-at text-muted mr-3"></i> {{ owner.email }}</li>
                     <li class="mb-2"><i class="fas fa-map-marker-alt text-muted mr-3"></i>Jamila 5 rue 70 n°412</li>
                     <li><i class="fas fa-phone text-muted mr-3"></i>0634102365</li>
                  </ul>
               </div>
            </div>
         </section>
      </div>
   </div>

   {# Separator #}
   <div class="row">
      <div class="col-md-7 col-sm-12">
         <hr class="my-5">
      </div>
   </div>

   <!-- Comment section -->
   <div class="row">
      <div class="col-md-7 col-sm-12">
         <section class="booking-comment">
            <div class="booking-comment__heading mb-5">
               <h3 class="mb-2">Commentaire public</h3>
               {% if isCommented == false %}
                  <p>
                     Vous pouvez dès maintenant mettre en place un superbe commentaire, et n'hésitez pas de mettre également en place une superbe note <strong>(5 étoiles si ça vous a plu)</strong>
                  </p>
               {% else %}
                  <p>
                     Vous pouvez dès maintenant modifier votre commentaire
                  </p>
                  <div class="booking-comment__content">
                     <div class="row">
                        <div class="col-lg-8">
                           <div class="row">
                              <div class="col-2">
                                 <div class="booking-comment__content-avatar">
                                    <img 
                                       src="/uploads/avatars/{{ user.avatar }}"
                                       class="rounded-circle img-fluid"
                                       alt="Photo de profil de {{ user.fullname }}"
                                    >
                                 </div>
                              </div>
                              <div class="col-10">
                                 <div class="booking-comment__content-details">
                                    <h6>{{ user.fullname }}</h6>
                                    <span class="booking-comment__content-details-rating text-warning">
                                       {{ include('/partials/rating.html.twig') }}
                                    </span>
                                    <small class="booking-comment__content-details-created-at text-muted">
                                       {{ comment.createdAt|date('D, d M Y') }}
                                    </small>
                                    <blockquote><em>{{ comment.content|raw }}</em></blockquote>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>

               {% endif %}
            </div>
            {% if isCommented == false %}
            <div class="booking-comment__form">
               {{ form_start(form) }}
                  <!-- Description field -->
                  <div class="form-outline">
                     {{ form_widget(form.content) }}
                     <small class="form-help">{{ form_help(form.content) }}</small>
                     {% if form_errors(form.content) is not empty %}
                        <div class="form-error mt-3">
                           {{ form_errors(form.content) }}
                        </div>
                     {% endif %}
                  </div>
                  <small 
                     class="text-muted mb-4 d-inline-block {% if form_errors(form.content) is not empty %}invisible{% endif %}">Entre <strong>10</strong> et <strong>200</strong> caractères
                  </small>

                  <!-- Rating field -->
                  <div class="form-outline">
                     {{ form_widget(form.rating) }}
                     <small class="form-help">{{ form_help(form.rating) }}</small>
                     {% if form_errors(form.rating) is not empty %}
                        <div class="form-error mt-3">
                           {{ form_errors(form.rating) }}
                        </div>
                     {% endif %}
                  </div>
                  <small 
                     class="text-muted mb-4 d-inline-block {% if form_errors(form.rating) is not empty %}invisible{% endif %}">Entre <strong>1</strong> et <strong>5</strong> étoiles
                  </small>

                  <!-- Submit button -->
                  <div class="form-outline">
                     <button class="btn btn-primary">
                        <i class="fas fa-plus mr-2"></i>
                        Nouveau commentaire
                     </button>
                  </div>
               {{ form_end(form) }}
            </div>
            {% endif %}
         </section>
      </div>
   </div>
</div>
{% endblock %}