src/Entity/User.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use App\Entity\Comment;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Cette addrese s'est déjà inscrit par un autre compte, veuillez taper un autre email"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *  min=3,
     *  max=18,
     *  minMessage="Le prénom doit faire au moins {{ limit }} caractères",
     *  maxMessage="Le prénom ne doit pas dépasser {{ limit }} caractères"
     * )
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *  min=3,
     *  max=18,
     *  minMessage="Le nom doit faire au moins {{ limit }} caractères",
     *  maxMessage="Le nom ne doit pas dépasser {{ limit }} caractères"
     * )
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez taper un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *  groups={"account_register"},
     *  min=8,
     *  max=25,
     *  minMessage="Le mot de passe doit faire au moins {{ limit }} caractères",
     *  maxMessage="Le mot de passe ne doit pas dépasser {{ limit }} caractères"
     * )
     */
    private $password;

    /**
     * @Assert\IdenticalTo(
     *  propertyPath="password",
     *  message="Veuillez confirmer correctement le mot de passe"
     * )
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $avatar;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *  min=300,
     *  minMessage="La description doit faire au moins {{ limit }} caractères"
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="owner", orphanRemoval=true)
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker", orphanRemoval=true)
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * Get Average rating
     *
     * @return integer|null
     */
    public function getAvgRating(): ?int
    {
        if (count($this->ads) > 0) {
            foreach ($this->ads as $ad) {
                $sumRating = array_reduce(
                    $ad->getComments()->toArray(),
                    fn($total, Comment $comment) => $total += $comment->getRating()
                );
    
                if (count($ad->getComments()) > 0) {
                    return ceil($sumRating / count($ad->getComments()));
                }
            }
        }

        return null;
    }

    /**
     * Set automaticaly createdAt value
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function setCreatedAtValue(): void 
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new DateTime();
        }
    }

    /**
     * create and set automaticaly slug value
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function setSlugValue(): void
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify
                            ->slugify($this->id . '-' . $this->firstName . '-' . $this->lastName);
        }
    } 

    /**
     * Retrieve the full name
     *
     * @return string
     */
    public function getFullname(): string 
    {   
        if ($this->firstName && $this->lastName) {
            return $this->firstName . ' ' . $this->lastName;
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPasswordConfirm(): ?string
    {
        return $this->passwordConfirm;
    }

    public function setConfirmPassword(string $passwordConfirm): self
    {
        $this->passwordConfirm = $passwordConfirm;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setOwner($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getOwner() === $this) {
                $ad->setOwner(null);
            }
        }

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->userRoles->map(function(Role $role) {
            return $role->getTitle();
        });

        $roles->add('ROLE_USER');

        return $roles->toArray();
    }

    public function getHash(): string
    {
        return $this->password;
    }

    public function getSalt() {}
    
    public function getUsername(): string
    {
        return $this->email;
    }

    public function eraseCredentials() {}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\User;
use App\Service\Uploader;
use App\Service\Paginator;
use App\Entity\PasswordUpdate;
use App\Repository\AdRepository;
use App\Repository\UserRepository;
use App\Form\AccountInfosEditionType;
use Symfony\Component\Form\FormError;
use App\Form\AccountAvatarEditionType;
use App\Form\AccountPasswordEditionType;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\AccountDescriptionEditionType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{

    /**
     * Allow to a user to edit its profile
     *
     * @Route("/user/edit-profile", name="account_edit_infos")
     * @IsGranted("ROLE_USER")
     * 
     * @param EntityManagerInterface $manager
     * @param Request $request
     * @return Response
     */
    public function editInfos(
        Request $request,
        EntityManagerInterface $manager
    ): Response
    {      
        // Get the user connected
        $user = $this->getUser();

        $form = $this
                    ->createForm(AccountInfosEditionType::class, $user)
                    ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager->persist($user);
            $manager->flush();

            $this->addFlash(
                'success',
                "Vos informations de base a été mis à jour avec succès. Veuillez donc vous reconnecter"
            );

            return $this->redirectToRoute("account_profile", [
                'slug' => $user->getSlug()
            ]);
        }

        return $this->render('user/edit_infos.html.twig', [
            'form' => $form->createView(),
            'user' => $user
        ]);
    }

    /**
     * Allow to edit user's avatar
     * 
     * @Route("/user/edit-avatar", name="account_edit_avatar")
     * @IsGranted("ROLE_USER")
     *
     * @param Request $request
     * @param Uploader $uploader
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function editAvatar(
        Request $request,
        Uploader $uploader,
        EntityManagerInterface $manager
    ): Response
    {
        $user = $this->getUser();

        // Create an object form
        $form = $this
                    ->createForm(AccountAvatarEditionType::class, $user)
                    ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile|null $avatar contains user's avatar */
            $avatar = $form->get('avatar')->getData();

            if ($avatar instanceof UploadedFile) {
                $newFilename = $uploader->upload(
                    $avatar,
                    $this->getParameter('avatars_directory')
                );

                $user->setAvatar($newFilename);
            }
            
            $manager->persist($user);
            $manager->flush();

            $this->addFlash(
                "success",
                "Vous avez été modifié votre photo de profil avec succès"
            );

            return $this->redirectToRoute("account_profile", [
                'slug' => $user->getSlug()
            ]);       
        }

        return $this->render("user/edit_avatar.html.twig", [
            'form' => $form->createView(),
            'user' => $user
        ]);
    }

    /**
     * Allow to edit user's description
     * 
     * @Route("/user/edit-description", name="account_edit_description")
     * @IsGranted("ROLE_USER")
     * 
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function editDescription(
        Request $request,
        EntityManagerInterface $manager
    ): Response
    {
        $user = $this->getUser();

        $form = $this
                    ->createForm(AccountDescriptionEditionType::class, $user)
                    ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager->persist($user);
            $manager->flush();

            $this->addFlash(
                "success",
                "Vous avez été modifié votre <strong>description</strong> de profil avec succès"
            );

            return $this->redirectToRoute("account_profile", [
                'slug' => $user->getSlug()
            ]);
        }

        return $this->render("/user/edit_description.html.twig", [
            'form' => $form->createView(),
            'user' => $user
        ]);
    }

    /**
     * Allow to edit user's password
     * 
     * @Route("/user/edit-password", name="account_edit_password")
     * @IsGranted("ROLE_USER")
     *
     * @param Request $request
     * @param UserPasswordEncoderInterface $encoder
     * @param EntityManagerInterface $manager
     * @return Response
     */
    public function editPassword(
        Request $request,
        UserPasswordEncoderInterface $encoder,
        EntityManagerInterface $manager
    )
    {
        // Connected user
        $user = $this->getUser();

        $password = new PasswordUpdate();

        // Create Form object and handle request
        $form = $this
                    ->createForm(AccountPasswordEditionType::class, $password)
                    ->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $passwordVerify = password_verify(
                                $password->getOldPassword(),
                                $user->getPassword()
            );

            if (!$passwordVerify) {
                $form
                    ->get('oldPassword')
                    ->addError(new FormError("Veuillez saisir correctment le mot de passe acutel"));
            } else {
                $newPassword = $password->getNewPassword();
                $encodedNewPassword = $encoder->encodePassword($user, $newPassword);
    
                $user->setPassword($encodedNewPassword);
    
                $manager->persist($user);
                $manager->flush();
    
                $this->addFlash(
                    'success',
                    "Vous avez été modifié votre <strong>mot de passe</strong> avec succès. Donc veuillez vous reconnecter"
                );
    
                return $this->redirectToRoute("account_login");
            }
            
        }

        return $this->render("user/edit_password.html.twig", [
            'form' => $form->createView(),
            'user' => $user
        ]);
    }

    /**
     * Allow to show the user's profile
     * 
     * @Route("/user/{slug}/{page<\d+>?1}", name="account_profile")
     * 
     * @param User $user
     * @param UserRepository $userRepository
     * @param Paginator $paginator
     * @param int $page
     * @return Response
     */
    public function profile(
        User $user,
        UserRepository $userRepository,
        Paginator $paginator,
        int $page
    ): Response
    {
        $paginator
            ->setEntityClassName(Ad::class)
            ->setOwner($user)
            ->setLimit(2)
            ->setCurrentPage($page);

        // All counters
        $counters  = $userRepository->getAllCounts($user->getId());

        return $this->render("user/profile.html.twig", [
            'user' => $user,
            'paginator' => $paginator,
            'commentsTotal' => $counters['commentsTotal'],               
            'bookingsTotal' => $counters['bookingsTotal'],
        ]);
    }
}

templates/user/edit_avatar.html.twig
{% extends 'base.html.twig' %}

{% block title %}
   Edition de photo de profile
{% endblock %}

{% form_theme form _self %}

{% block body %}
<div class="container mt-5">
   <div class="row align-items-center">
      <!-- User's profile -->
      <div class="col-md-3">
         {{ include('side nav/side-nav-profile.html.twig') }}
      </div>
      <!-- Edit form -->
      <div class="col-md-9">
         <div class="row justify-content-center">
            <div class="col-md-10">
               <div class="user-edit__avatar">
                  <div class="user-edit__avatar-heading text-center mb-5">
                     <h4>Photo de profil public</h4>
                     <p>Vous pouvez modifier votre photo de profil en mettant une autre photo sympa</p>
                  </div>
                  <div class="user-edit__avatar-form-edit">
                     {{ form_start(form) }}
                        <p class="mb-2">
                           Cliquer sur <strong>browse</strong> afin que vous puissiez la modifier
                        </p>
                        <!-- Avatar field -->
                        <div class="form-outline">
                           {{ form_widget(form.avatar) }}
                           {{ form_label(form.avatar, null, {
                              'label_attr': {
                                 'class': 'form-label'
                              }
                           }) }}
                           <small class="form-help">{{ form_help(form.avatar) }}</small>
                           {% if form_errors(form.avatar) is not empty %}
                              <div class="form-error mt-3">
                                 {{ form_errors(form.avatar) }}
                              </div>
                           {% endif %}
                        </div>
                        <small 
                           class="text-muted mb-4 d-inline-block {% if form_errors(form.avatar) is not empty %}invisible{% endif %}"><strong>JPEG / 2MO</strong>
                        </small>

                        <!-- Backup button -->
                        <button class="btn btn-primary d-block">
                           <i class="fas fa-save mr-2"></i>
                           Sauvegarder
                        </button>
                     {{ form_end(form) }}
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

templates/user/edit_description.html.twig
{% extends 'base.html.twig' %}

{% block title %}
   Edition de description
{% endblock %}

{% form_theme form _self %}

{% block body %}
<div class="container mt-5">
   <div class="row align-items-center">
      <!-- User's profile -->
      <div class="col-md-3">
         {{ include('side nav/side-nav-profile.html.twig') }}
      </div>
      <!-- Edit form -->
      <div class="col-md-9">
         <div class="row justify-content-center">
            <div class="col-md-10">
               <div class="user-edit__description">
                  <div class="user-edit__description-heading text-center mb-5">
                     <h4>Description de profil public</h4>
                     <p>Vous pouvez modifier votre description de profil en mettant une autre superbe description</p>
                  </div>
                  <div class="user-edit__description-form-edit">
                     {{ form_start(form) }}
                        <h6 class="mb-2">Description</h6>
                        <!-- Avatar field -->
                        <div class="form-outline">
                           {{ form_widget(form.description) }}
                           <small class="form-help">{{ form_help(form.description) }}</small>
                           {% if form_errors(form.description) is not empty %}
                              <div class="form-error mt-3">
                                 {{ form_errors(form.description) }}
                              </div>
                           {% endif %}
                        </div>
                        <small 
                           class="text-muted mb-4 d-inline-block {% if form_errors(form.description) is not empty %}invisible{% endif %}">Plus de <strong>300</strong> caractères
                        </small>

                        <!-- Backup button -->
                        <button class="btn btn-primary d-block">
                           <i class="fas fa-save mr-2"></i>
                           Sauvegarder
                        </button>
                     {{ form_end(form) }}
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

templates/user/edit_infos.html.twig
{% extends 'base.html.twig' %}

{% block title %}
   Edition d'informations de base
{% endblock %}

{% form_theme form _self %}

{% block body %}
<div class="container mt-5">
   <div class="row align-items-center">
      <!-- User's profile -->
      <div class="col-md-3">
         {{ include('side nav/side-nav-profile.html.twig') }}
      </div>
      <!-- Edit form -->
      <div class="col-md-9">
         <div class="row justify-content-center">
            <div class="col-md-10">
               <div class="user-edit__profile">
                  <div class="user-edit__profile-heading text-center mb-5">
                     <h4>Profil public</h4>
                     <p>Vous pouvez modifier vos informations de base qui vous concernent</p>
                  </div>
                  <div class="user-edit__profile-form-edit">
                     {{ form_start(form) }}
                        <!-- First name & last name fields -->
                        <h6 class="mb-3">Informations de base</h6>
                        <div class="row mb-4">
                           <!-- First name fields -->
                           <div class="col">
                              <div class="form-outline">
                                 {{ form_widget(form.firstName) }}
                                 {{ form_label(form.firstName, null, {
                                    'label_attr': {
                                       'class': 'form-label'
                                    }
                                 }) }}
                                 <small class="form-help">{{ form_help(form.firstName) }}</small>
                                 {% if form_errors(form.firstName) is not empty %}
                                    <div class="form-error mt-3">
                                       {{ form_errors(form.firstName) }}
                                    </div>
                                 {% endif %}
                                 <div class="form-helper"></div>
                              </div>
                              <small 
                                 class="text-muted {% if form_errors(form.firstName) is not empty %}invisible{% endif %}">Entre <strong>3</strong> et <strong>18</strong> caractères
                              </small>
                           </div>
                           <!-- Last name field -->
                           <div class="col">
                              <div class="form-outline">
                                 {{ form_widget(form.lastName) }}
                                 {{ form_label(form.lastName, null, {
                                    'label_attr': {
                                       'class': 'form-label'
                                    }
                                 }) }}
                                 <small class="form-help">{{ form_help(form.lastName) }}</small>
                                 {% if form_errors(form.lastName) is not empty %}
                                    <div class="form-error mt-3">
                                       {{ form_errors(form.lastName) }}
                                    </div>
                                 {% endif %}
                              </div>
                              <small 
                                 class="text-muted {% if form_errors(form.firstName) is not empty %}invisible{% endif %}">Entre <strong>3</strong> et <strong>18</strong> caractères
                              </small>
                           </div>
                        </div>
      
                        <!-- Email field -->
                        <div class="form-outline">
                           {{ form_widget(form.email) }}
                           {{ form_label(form.email, null, {
                              'label_attr': {
                                 'class': 'form-label'
                              }
                           }) }}
                           <small class="form-help">{{ form_help(form.email) }}</small>
                           {% if form_errors(form.email) is not empty %}
                              <div class="form-error mt-3">
                                 {{ form_errors(form.email) }}
                              </div>
                           {% endif %}
                        </div>
                        <small 
                           class="text-muted mb-4 d-inline-block {% if form_errors(form.email) is not empty %}invisible{% endif %}">Un <strong>email valide</strong>
                        </small>

                        <!-- Keep button -->
                        <button class="btn btn-primary d-block">
                           <i class="fas fa-save mr-2"></i>
                           Sauvegarder
                        </button>
                     {{ form_end(form) }}
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock %}

templates/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}
   {{ user.fullname }}
{% endblock %}

{% block body %}
<div class="container mt-5">
   <div class="row">
      <!-- User's infos -->
      <div class="col-md-3 col-sm-12 mb-5">
         <div class="user-profile__infos">
            <div class="user-profile__infos-avatar text-center">
               <img 
                  src="/uploads/avatars/{{ user.avatar }}" 
                  alt="Photo de profil de {{ user.fullname }}"
                  class="p-1 border rounded-circle mb-3">
               <h6>{{ user.fullname }}</h6>
            </div>
            <hr class="my-3">
            <div class="user-profile__infos-details">
               <ul class="list-group list-unstyled">
                  <li class="py-2">
                     <i class="fas fa-star mr-3 text-warning"></i>
                     <strong>
                     {% if user.avgRating > 0 %}
                        {{ user.avgRating }}
                     {% else %}
                        --
                     {% endif %}
                     </strong> 
                     Note de propriétaire
                  </li>
                  <li class="py-2">
                     <i class="fas fa-house-user mr-3 text-warning"></i>
                     <strong>
                     {% if user.ads|length > 0 %}
                        {{ user.ads|length }}
                     {% else %}
                        --
                     {% endif %}
                     </strong> 
                     Total de logements
                  </li>
                  <li class="py-2">
                     <i class="fas fa-user mr-3 text-warning"></i>
                     <strong>
                     {% if bookingsTotal > 0 %}
                        {{ bookingsTotal }}
                     {% else %}
                        --
                     {% endif %}
                     </strong> 
                     Total de voyageurs
                  </li>
                  <li class="py-2">
                     <i class="fas fa-comment mr-3 text-warning"></i>
                     <strong>
                     {% if commentsTotal > 0 %}
                        {{ commentsTotal }}
                     {% else %}
                        --
                     {% endif %}
                     </strong> 
                     Total de commentaires
                  </li>
               </ul>
            </div>
         </div>
      </div>
      <div class="col-md-1">
         <div class="vertical-separator"></div>
      </div>
      <!-- User's description -->
      <div class="col-md-8 col-sm-12">
         <div class="user-profile__description">
            <h3>Informations personnelles</h3>
            <p>{{ user.description|raw }}</p>
         </div>
      </div>
   </div>
   
   {# User's ads #}
   <div class="row justify-content-end">
      <div class="col-md-8">
         <hr class="my-5">
         <div class="user-profile__ads">
            {% if user.ads|length > 0 %}
            <div class="row">
               <h6 class="mb-2">Mes annonces ({{ user.ads|length }})</h6>
               {% for ad in paginator.fetchItems %}
               <div class="col-md-6 mb-3">
                  {{ include('cards/ad_card.html.twig') }}
               </div>
               {% endfor %}
            </div>
            {% else %}
               {% if app.user == user %}
                  <p>
                     Vous n'avez pas encore d'annonces à afficher. Vous pouvez dès maintenant créer une annonce
                  </p>
                  <a 
                     href="{{ path('ad_create') }}"
                     class="btn btn-primary">
                     <i class="fas fa-plus mr-2"></i>
                     Créer une annonce
                  </a>
               {% else %}
                  <p>Cet utilisateur ne possède pas encore d'annonces</p>
               {% endif %}
            {% endif %}
         </div>
      </div>
   </div>

   <!-- Pagination -->
   {% if paginator.calculatePages > 1 %}
      {{ paginator.render() }}
   {% endif %}
</div>
{% endblock %}